/* eslint-disable sort-keys-fix/sort-keys-fix,@typescript-eslint/no-var-requires */

import type { Inventory } from '../../../domain/Inventory'

export const exportedStats: Record<string, Inventory> = {
  maincharacter1744304617534: {
    id: 'maincharacter1744304617534',
    name: 'Knee Knife',
    items: {
      'Basic accessories': {
        cost: 0,
        name: 'Basic accessories',
        weight: 8,
        quantity: 2,
      },
      Leather: {
        cost: 5,
        name: 'Leather',
        weight: 25,
        ascArmorClass: 2,
        quantity: 1,
      },
      'Arrows (20)': {
        cost: 2,
        name: 'Arrows (20)',
        weight: 1,
        damage: 'd6',
        flags: 16,
        quantity: 1,
      },
      'Bow, Short': {
        cost: 15,
        name: 'Bow, Short',
        weight: 5,
        damage: '',
        flags: 16,
        quantity: 1,
      },
      'Sword, Long': {
        cost: 15,
        name: 'Sword, Long',
        weight: 10,
        damage: 'd8',
        flags: 8,
        quantity: 1,
      },
      'Oil, lamp (1 pint)': {
        cost: 0.1,
        name: 'Oil, lamp (1 pint)',
        weight: 1,
        quantity: 3,
      },
      'Rations, trail': {
        cost: 1,
        name: 'Rations, trail',
        weight: 2,
        quantity: 5,
      },
    },
    character: {
      gold: 900,
      hitPoints: 11,
      stats: {
        Strength: {
          Score: 10,
          ToHit: 0,
          Damage: 0,
          Doors: '1-2',
          Carry: 5,
        },
        Dexterity: {
          Score: 14,
          MissilesToHit: 1,
          ArmorClass: 1,
        },
        Constitution: {
          Score: 9,
          HitPoints: 0,
          RaiseDeadSurvivalChance: '75%',
        },
        Intelligence: {
          Score: 8,
          MaxAdditionalLanguages: 1,
          MaxSpellLevel: 5,
          NewSpellUnderstandingChance: 40,
          SpellsPerLevel: '3/5',
        },
        Wisdom: {
          Score: 14,
        },
        Charisma: {
          Score: 7,
          MaxNumberOfSpecialHirelings: 3,
        },
      },
      level: 1,
      classDef: {
        name: 'Thief',
        PrimeAttr: [['Dexterity', 13]],
        SavingThrow: {
          snw: {
            value: 15,
            details: '+2 against devices, including traps, magical wands or staffs, and other magical devices',
          },
          alternative: {
            DeathRaysAndPoison: 13,
            Wands: 14,
            TurnedToStone: 13,
            DragonsBreath: 16,
            SpellsAndStaffs: 15,
          },
        },
        HitDice: 4,
        ArmorPermitted: 'Leather armor only; no shield',
        WeaponsPermitted: 'All, but magical weapons are limited to daggers and swords',
        Race: ['Human', 'Dwarf', 'Elf', 'HalfElf', 'Hobbit'],
        Alignment: ['Neutral', 'Chaotic'],
      },
      ancestry: 'Human',
      toHit: {
        melee: '0',
        missiles: '+1',
      },
      alignment: 'Neutral',
      armorClass: {
        aac: 10,
        armor: 'None',
        dac: 9,
      },
      damageMod: '0',
      experiencePoints: 0,
      experiencePointsBonus: 10,
      $classDefName: 'Thief',
    },
    isCompact: false,
  },
  'character-name1744321152145': {
    id: 'character-name1744321152145',
    name: 'Blue Doar',
    items: {
      'Basic accessories': {
        cost: 0,
        name: 'Basic accessories',
        weight: 8,
        quantity: 2,
      },
      Dagger: {
        cost: 2,
        name: 'Dagger',
        weight: 2,
        flags: 4,
        damage: 'd4',
        quantity: 1,
      },
      Staff: {
        cost: 0,
        name: 'Staff',
        weight: 10,
        damage: 'd6',
        flags: 8,
        quantity: 1,
      },
      'Spellbook, blank': {
        cost: 25,
        name: 'Spellbook, blank',
        weight: 1,
        quantity: 1,
      },
      Backpack: {
        cost: 5,
        name: 'Backpack',
        weight: 2,
        quantity: 1,
      },
      Bedroll: {
        cost: 1,
        name: 'Bedroll',
        weight: 5,
        quantity: 1,
      },
      Candle: {
        cost: 0.01,
        name: 'Candle',
        weight: 0.5,
        quantity: 5,
      },
      'Case (map or scroll)': {
        cost: 1,
        name: 'Case (map or scroll)',
        weight: 1,
        quantity: 1,
      },
      'Flask, leather': {
        cost: 0.03,
        name: 'Flask, leather',
        weight: 0.5,
        quantity: 1,
      },
      'Flint & steel': {
        cost: 1,
        name: 'Flint & steel',
        weight: 1,
        quantity: 1,
      },
      'Ink (1-ounce bottle)': {
        cost: 1,
        name: 'Ink (1-ounce bottle)',
        weight: 0.1,
        quantity: 1,
      },
      'Lantern, bullseye': {
        cost: 12,
        name: 'Lantern, bullseye',
        weight: 3,
        quantity: 1,
      },
      Mirror: {
        cost: 20,
        name: 'Mirror',
        weight: 0.5,
        quantity: 1,
      },
      'Oil, lamp (1 pint)': {
        cost: 0.1,
        name: 'Oil, lamp (1 pint)',
        weight: 1,
        quantity: 1,
      },
      'Parchment (sheet)': {
        cost: 0.2,
        name: 'Parchment (sheet)',
        weight: 0.5,
        quantity: 5,
      },
      'Rations, trail': {
        cost: 1,
        name: 'Rations, trail',
        weight: 2,
        quantity: 7,
      },
      Waterskin: {
        cost: 1,
        name: 'Waterskin',
        weight: 2,
        quantity: 1,
      },
    },
    character: {
      gold: 120,
      hitPoints: 3,
      stats: {
        Strength: {
          Score: 8,
          ToHit: 0,
          Damage: 0,
          Doors: '1-2',
          Carry: 0,
        },
        Dexterity: {
          Score: 11,
          MissilesToHit: 0,
          ArmorClass: 0,
        },
        Constitution: {
          Score: 12,
          HitPoints: 0,
          RaiseDeadSurvivalChance: '75%',
        },
        Intelligence: {
          Score: 14,
          MaxAdditionalLanguages: 4,
          MaxSpellLevel: 7,
          NewSpellUnderstandingChance: 65,
          SpellsPerLevel: '5/8',
        },
        Wisdom: {
          Score: 9,
        },
        Charisma: {
          Score: 9,
          MaxNumberOfSpecialHirelings: 4,
        },
      },
      level: 1,
      classDef: {
        name: 'MagicUser',
        PrimeAttr: [['Intelligence', 13]],
        SavingThrow: {
          snw: {
            value: 15,
            details: '+2 against spells, including spells from magic wands and staffs',
          },
          alternative: {
            DeathRaysAndPoison: 13,
            Wands: 14,
            TurnedToStone: 13,
            DragonsBreath: 16,
            SpellsAndStaffs: 15,
          },
        },
        HitDice: 4,
        ArmorPermitted: 'None',
        WeaponsPermitted: 'Dagger, staff, and darts',
        Race: ['Elf', 'HalfElf', 'Human'],
        Alignment: ['Chaotic', 'Neutral', 'Lawful'],
        $isCaster: true,
        $spellsAtTheFirstLevel: 1,
      },
      ancestry: 'Human',
      toHit: {
        melee: '0',
        missiles: '0',
      },
      alignment: 'Neutral',
      armorClass: {
        aac: 10,
        armor: 'None',
        dac: 9,
      },
      damageMod: '0',
      experiencePoints: 0,
      experiencePointsBonus: 5,
      spells: {
        Shield: {
          name: 'Shield',
          level: 1,
        },
        'Read Magic': {
          name: 'Read Magic',
          level: 1,
        },
        'Read Languages': {
          name: 'Read Languages',
          level: 1,
        },
        'Hold Portal': {
          name: 'Hold Portal',
          level: 1,
        },
        'Charm Person': {
          name: 'Charm Person',
          level: 1,
        },
        'Protection from Evil': {
          name: 'Protection from Evil',
          level: 1,
        },
        'Detect Magic': {
          name: 'Detect Magic',
          level: 1,
        },
        'Magic Missile': {
          name: 'Magic Missile',
          level: 1,
        },
      },
      $classDefName: 'MagicUser',
    },
    isCompact: false,
  },
  'character-name1744321460655': {
    id: 'character-name1744321460655',
    name: 'Mighty Fighter',
    items: {
      'Basic accessories': {
        cost: 0,
        name: 'Basic accessories',
        weight: 8,
        quantity: 1,
      },
      Chain: {
        cost: 75,
        name: 'Chain',
        weight: 50,
        ascArmorClass: 4,
        quantity: 1,
      },
      Spear: {
        cost: 1,
        name: 'Spear',
        weight: 10,
        flags: 7,
        damage: 'd6',
        quantity: 1,
      },
      Dagger: {
        cost: 2,
        name: 'Dagger',
        weight: 2,
        flags: 4,
        damage: 'd4',
        quantity: 1,
      },
      Bedroll: {
        cost: 1,
        name: 'Bedroll',
        weight: 5,
        quantity: 1,
      },
      'Rations, trail': {
        cost: 1,
        name: 'Rations, trail',
        weight: 2,
        quantity: 7,
      },
      Torch: {
        cost: 0.01,
        name: 'Torch',
        weight: 1,
        quantity: 5,
      },
    },
    character: {
      gold: 100,
      hitPoints: 1,
      stats: {
        Strength: {
          Score: 13,
          ToHit: 1,
          Damage: 0,
          Doors: '1-2',
          Carry: 10,
        },
        Dexterity: {
          Score: 8,
          MissilesToHit: -1,
          ArmorClass: -1,
        },
        Constitution: {
          Score: 10,
          HitPoints: 0,
          RaiseDeadSurvivalChance: '75%',
        },
        Intelligence: {
          Score: 13,
          MaxAdditionalLanguages: 3,
          MaxSpellLevel: 7,
          NewSpellUnderstandingChance: 65,
          SpellsPerLevel: '5/8',
        },
        Wisdom: {
          Score: 10,
        },
        Charisma: {
          Score: 8,
          MaxNumberOfSpecialHirelings: 3,
        },
      },
      level: 1,
      classDef: {
        name: 'Fighter',
        PrimeAttr: [['Strength', 13]],
        SavingThrow: {
          snw: {
            value: 15,
            details: '+1 bonus on all saving throws except against spells (including those from wands and staffs)',
          },
          alternative: {
            DeathRaysAndPoison: 12,
            Wands: 13,
            TurnedToStone: 14,
            DragonsBreath: 15,
            SpellsAndStaffs: 16,
          },
        },
        HitDice: 8,
        ArmorPermitted: 'Any',
        WeaponsPermitted: 'Any',
        Race: ['Human', 'Dwarf', 'Elf', 'HalfElf', 'Hobbit'],
        Alignment: ['Chaotic', 'Neutral', 'Lawful'],
      },
      ancestry: 'Human',
      toHit: {
        melee: '+1',
        missiles: '0',
      },
      alignment: 'Neutral',
      armorClass: {
        aac: 10,
        armor: 'None',
        dac: 9,
      },
      damageMod: '0',
      experiencePoints: 0,
      experiencePointsBonus: 5,
      $classDefName: 'Fighter',
    },
    isCompact: false,
  },
}
