name: Build, test and lint

on:
  push:
    branches:
      - '**'

jobs:
  run-linters:
    name: Linter and tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter and check format
        run: yarn format

      - name: Run tests
        run: yarn test
